language: go
go:
  - 1.2
  - 1.3
  - release
  - tip
env:
  global:
    - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
before_install:
  - go get github.com/tools/godep
  - godep restore
script:
  - go test -v ./...
