language: go
go:
  - 1.3
  - release
  - tip
before_install:
  - go get github.com/tools/godep
  - godep restore
  # Release/1.3
  - go get code.google.com/p/go.tools/cmd/vet
  # Tip
  - go get golang.org/x/tools/cmd/vet
script:
  - make check
  - make test
